use std::collections::HashMap;

use lazy_static::lazy_static;

use crate::model::card::{Card, CardId};
use crate::model::card::card_builder::CardBuilder;
use crate::model::game_data::board::tile::Tile;
use crate::model::game_data::board::tile::Tile::{Greenery, Ocean};
use crate::model::game_data::mutation::normal_mutation::NormalMutation::{CardDrawMutation, OxygenIncreaseMutation, ProductionMutation, ResourceMutation, TemperatureIncreaseMutation, TileQueuingMutation, TrMutation};
use crate::model::game_data::requirement::Requirement;
use crate::model::resource::Resource::{Energy, Heat, MegaCredit, Plant, Steel, Titanium};
use crate::model::tag::Tag;
use crate::model::tag::Tag::{Builder, City, Earth, Jovian, Microbe, Power, Science, Space};

lazy_static! {
    pub static ref CARD_COMPENDIUM: HashMap<CardId, Card> = build_card_compendium();
}

fn build_card_compendium() -> HashMap<CardId, Card> {
    HashMap::from([
        (1, CardBuilder::new()
            .id(1)
            .cost(8)
            .tags(vec![Jovian, Builder])
            .requirement(Requirement::MaxOxygen(5))
            .victory_points(2)
            .build()),
        (3, CardBuilder::new()
            .id(3)
            .cost(13)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(Energy, 1))
            .mutation(TemperatureIncreaseMutation)
            .build()),
        (4, CardBuilder::new()
            .id(4)
            .cost(13)
            .requirement(Requirement::MinOcean(3))
            .mutation(ProductionMutation(MegaCredit, -1))
            .mutation(ProductionMutation(Plant, 2))
            .build()),
        (9, space_event()
            .cost(14)
            .mutation(TemperatureIncreaseMutation)
            .mutation(ResourceMutation(Titanium, 2))
            .build()),
        (10, space_event()
            .cost(21)
            .mutation(TemperatureIncreaseMutation)
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (11, space_event()
            .cost(27)
            .mutation(TemperatureIncreaseMutation)
            .mutation(TemperatureIncreaseMutation)
            .mutation(ResourceMutation(Titanium, 4))
            .build()),
        (16, martian_city()
            .cost(24)
            .requirement(Requirement::MaxOxygen(7))
            .mutation(ProductionMutation(MegaCredit, 3))
            .mutation(ResourceMutation(Plant, 3))
            .victory_points(1)
            .build()),
        (17, martian_city()
            .cost(18)
            .mutation(ProductionMutation(MegaCredit, 3))
            .build()),
        (18, CardBuilder::new()
            .id(8)
            .cost(28)
            .tags(vec![Jovian, Space])
            .requirement(Requirement::MinOxygen(2))
            .mutation(ProductionMutation(Heat, 2))
            .mutation(ProductionMutation(Plant, 2))
            .victory_points(2)
            .build()),
        (19, space_event()
            .tags(vec![Earth])
            .mutation(ResourceMutation(Plant, 3))
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (22, CardBuilder::new()
            .id(2)
            .cost(15)
            .mutation(ProductionMutation(MegaCredit, -2))
            .mutation(ProductionMutation(Heat, 3))
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (26, CardBuilder::new()
            .id(6)
            .cost(16)
            .tags(vec![Tag::Plant, Builder])
            .requirement(Requirement::MinTemperature(-12))
            .mutation(ResourceMutation(Plant, 3))
            .mutation(ProductionMutation(MegaCredit, 2))
            .victory_points(1)
            .build()),
        (29, martian_city()
            .cost(16)
            .requirement(Requirement::MaxOxygen(9))
            .mutation(ProductionMutation(MegaCredit, 3))
            .build()),
        (30, CardBuilder::new()
            .id(0)
            .cost(13)
            .tags(vec![Earth, Power])
            .mutation(ProductionMutation(MegaCredit, -2))
            .mutation(ProductionMutation(Heat, 2))
            .mutation(ProductionMutation(Energy, 2))
            .build()),
        (32, martian_city()
            .cost(18)
            .mutation(ProductionMutation(Energy, -1))
            .mutation(ProductionMutation(Steel, 2))
            .build()),
        (36, CardBuilder::new()
            .id(6)
            .cost(14)
            .event()
            .mutation(TrMutation(2))
            .build()),
        (37, space_event()
            .cost(31)
            .mutation(ProductionMutation(Plant, 1))
            .mutation(TrMutation(2))
            .mutation(TemperatureIncreaseMutation)
            .build()),
        (39, space_event()
            .cost(31)
            .mutation(TemperatureIncreaseMutation)
            .mutation(TemperatureIncreaseMutation)
            .mutation(TemperatureIncreaseMutation)
            .mutation(ResourceMutation(Steel, 4))
            .build()),
        (40, CardBuilder::new()
            .id(0)
            .cost(30)
            .tags(vec![Jovian, Space])
            .mutation(ProductionMutation(Titanium, 2))
            .victory_points(2)
            .build()),
        (41, CardBuilder::new()
            .id(1)
            .cost(12)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Plant, -1))
            .mutation(ProductionMutation(MegaCredit, 4))
            .victory_points(1)
            .build()),
        (42, CardBuilder::new()
            .id(2)
            .cost(6)
            .tags(vec![Microbe])
            .requirement(Requirement::MaxTemperature(-18))
            .mutation(ProductionMutation(Plant, 1))
            .build()),
        (43, CardBuilder::new()
            .id(3)
            .cost(6)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -1))
            .mutation(ProductionMutation(Heat, 3))
            .build()),
        (45, CardBuilder::new()
            .id(5)
            .cost(10)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(MegaCredit, -2))
            .mutation(ProductionMutation(Energy, 3))
            .build()),
        (47, CardBuilder::new()
            .id(7)
            .cost(10)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinOcean(5))
            .mutation(ProductionMutation(Plant, 2))
            .mutation(ResourceMutation(Plant, 1))
            .build()),
        (48, CardBuilder::new()
            .id(8)
            .cost(9)
            .tags(vec![Tag::Plant])
            .mutation(ProductionMutation(Plant, 1))
            .build()),
        (53, CardBuilder::new()
            .id(3)
            .cost(18)
            .requirement(Requirement::MinTemperature(0))
            .mutation(TileQueuingMutation(Ocean))
            .mutation(TileQueuingMutation(Ocean))
            .victory_points(2)
            .build()),
        (55, CardBuilder::new()
            .id(5)
            .cost(17)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinOcean(6))
            .mutation(ProductionMutation(MegaCredit, 2))
            .mutation(ProductionMutation(Plant, 3))
            .mutation(ResourceMutation(Plant, 2))
            .victory_points(1)
            .build()),
        (58, CardBuilder::new()
            .id(8)
            .cost(32)
            .tags(vec![Jovian, Space, Power])
            .requirement(Requirement::Tag(Jovian, 1))
            .mutation(ProductionMutation(Heat, 3))
            .mutation(ProductionMutation(Energy, 3))
            .victory_points(1)
            .build()),
        (60, CardBuilder::new()
            .id(0)
            .cost(13)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-4))
            .mutation(ProductionMutation(Plant, 3))
            .mutation(ResourceMutation(Plant, 1))
            .victory_points(1)
            .build()),
        (63, CardBuilder::new()
            .id(3)
            .cost(12)
            .event()
            .mutation(OxygenIncreaseMutation)
            .mutation(ResourceMutation(Steel, 2))
            .build()),
        (75, space_event()
            .cost(23)
            .mutation(OxygenIncreaseMutation)
            .mutation(TileQueuingMutation(Ocean))
            .mutation(ResourceMutation(Plant, 2))
            .build()),
        (77, CardBuilder::new()
            .id(7)
            .cost(11)
            .tags(vec![Science, Space, Power])
            .mutation(ProductionMutation(Energy, 1))
            .mutation(ResourceMutation(Titanium, 2))
            .build()),
        (78, space_event()
            .cost(23)
            .mutation(TileQueuingMutation(Ocean))
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (80, space_event()
            .cost(36)
            .mutation(TileQueuingMutation(Ocean))
            .mutation(TileQueuingMutation(Ocean))
            .mutation(TemperatureIncreaseMutation)
            .mutation(TemperatureIncreaseMutation)
            .build()),
        (83, CardBuilder::new()
            .id(3)
            .cost(17)
            .tags(vec![Power, Space])
            .mutation(ProductionMutation(Energy, 3))
            .build()),
        (87, CardBuilder::new()
            .id(7)
            .cost(11)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-16))
            .mutation(ProductionMutation(Plant, 1))
            .mutation(ResourceMutation(Plant, 3))
            .build()),
        (88, CardBuilder::new()
            .id(8)
            .cost(6)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-14))
            .mutation(ProductionMutation(Plant, 1))
            .mutation(ResourceMutation(Plant, 1))
            .build()),
        (89, CardBuilder::new()
            .id(9)
            .cost(7)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(MegaCredit, -1))
            .mutation(ProductionMutation(Energy, 2))
            .build()),
        (93, CardBuilder::new()
            .id(3)
            .cost(10)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-10))
            .mutation(ProductionMutation(Plant, 2))
            .mutation(ResourceMutation(Plant, 2))
            .build()),
        (100, CardBuilder::new()
            .id(0)
            .cost(1)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(MegaCredit, -1))
            .mutation(ProductionMutation(Energy, 1))
            .build()),
        (108, martian_city()
            .requirement(Requirement::MinOxygen(12))
            .mutation(ProductionMutation(MegaCredit, 4))
            .mutation(ResourceMutation(Plant, 2))
            .victory_points(1)
            .build()),
        (113, CardBuilder::new()
            .id(3)
            .cost(11)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(Energy, 1))
            .victory_points(1)
            .build()),
        (114, CardBuilder::new()
            .id(4)
            .cost(11)
            .tags(vec![Science])
            .requirement(Requirement::MinOxygen(7))
            .victory_points(2)
            .build()),
        (117, CardBuilder::new()
            .id(7)
            .cost(11)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(Energy, 2))
            .build()),
        (118, CardBuilder::new()
            .id(8)
            .cost(16)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(4))
            .mutation(ProductionMutation(MegaCredit, 2))
            .mutation(ProductionMutation(Plant, 2))
            .mutation(ResourceMutation(Plant, 2))
            .victory_points(2)
            .build()),
        (119, CardBuilder::new()
            .id(9)
            .cost(2)
            .requirement(Requirement::MaxOcean(3))
            .victory_points(1)
            .build()),
        (122, CardBuilder::new()
            .id(2)
            .cost(4)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinOcean(3))
            .mutation(ProductionMutation(Plant, 1))
            .mutation(ResourceMutation(Plant, -1))
            .build()),
        (126, CardBuilder::new()
            .id(6)
            .cost(11)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -1))
            .mutation(ProductionMutation(Heat, 4))
            .build()),
        (127, CardBuilder::new()
            .id(7)
            .cost(11)
            .event()
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (132, CardBuilder::new()
            .id(2)
            .cost(14)
            .tags(vec![Science, Power, Builder])
            .requirement(Requirement::Tag(Power, 2))
            .mutation(ProductionMutation(Energy, 3))
            .build()),
        (136, CardBuilder::new()
            .id(6)
            .cost(4)
            .tags(vec![Power, Builder])
            .mutation(ProductionMutation(Energy, 1))
            .build()),
        (143, space_event()
            .tags(vec![Earth])
            .mutation(TileQueuingMutation(Ocean))
            .mutation(CardDrawMutation(2))
            .mutation(ResourceMutation(Plant, 5))
            .victory_points(2)
            .build()),
        (145, CardBuilder::new()
            .id(5)
            .cost(18)
            .tags(vec![Power, Builder])
            .requirement(Requirement::Tag(Science, 2))
            .mutation(ProductionMutation(Energy, 3))
            .victory_points(1)
            .build()),
        (146, CardBuilder::new()
            .id(6)
            .cost(8)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinOcean(3))
            .mutation(ProductionMutation(Plant, 2))
            .mutation(ResourceMutation(Plant, -2))
            .build()),
        (155, CardBuilder::new()
            .id(5)
            .cost(16)
            .tags(vec![Science, Microbe])
            .requirement(Requirement::MaxTemperature(-14))
            .mutation(ProductionMutation(Plant, 2))
            .build()),
        (158, CardBuilder::new()
            .id(8)
            .cost(12)
            .tags(vec![Microbe, Builder])
            .mutation(ProductionMutation(Energy, 1))
            .mutation(ProductionMutation(Steel, 1))
            .build()),
        (159, CardBuilder::new()
            .id(9)
            .cost(7)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-24))
            .mutation(ResourceMutation(Plant, 1))
            .build()),
        (161, space_event()
            .cost(15)
            .mutation(TileQueuingMutation(Ocean))
            .mutation(CardDrawMutation(1))
            .build()),
        (162, space_event()
            .cost(7)
            .tags(vec![Earth])
            .mutation(ProductionMutation(Heat, 2))
            .build()),
        (168, CardBuilder::new()
            .id(8)
            .cost(6)
            .tags(vec![Power, Builder])
            .requirement(Requirement::MinOxygen(7))
            .mutation(ProductionMutation(Energy, 1))
            .victory_points(1)
            .build()),
        (169, CardBuilder::new()
            .id(9)
            .cost(16)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::MinTemperature(-6))
            .mutation(ProductionMutation(Plant, 1))
            .mutation(ProductionMutation(MegaCredit, 2))
            .mutation(ResourceMutation(Plant, 1))
            .victory_points(2)
            .build()),
        (170, space_event()
            .cost(26)
            .mutation(ProductionMutation(Heat, 3))
            .mutation(ProductionMutation(Plant, 1))
            .build()),
        (171, CardBuilder::new()
            .id(1)
            .cost(5)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -2))
            .mutation(ProductionMutation(Plant, 1))
            .mutation(TrMutation(1))
            .build()),
        (176, CardBuilder::new()
            .id(6)
            .cost(10)
            .tags(vec![Tag::Plant, Builder])
            .requirement(Requirement::MinTemperature(-20))
            .mutation(ProductionMutation(MegaCredit, 1))
            .mutation(ResourceMutation(Plant, 2))
            .victory_points(1)
            .build()),
        (179, CardBuilder::new()
            .id(9)
            .cost(9)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -1))
            .mutation(ProductionMutation(Plant, 1))
            .build()),
        (180, CardBuilder::new()
            .id(0)
            .cost(6)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -1))
            .mutation(ProductionMutation(Titanium, 1))
            .mutation(ProductionMutation(MegaCredit, 1))
            .build()),
        (181, CardBuilder::new()
            .id(1)
            .cost(5)
            .event()
            .requirement(Requirement::MinTemperature(2))
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (182, martian_city()
            .mutation(ProductionMutation(MegaCredit, 3))
            .victory_points(-2)
            .build()),
        (190, CardBuilder::new()
            .id(0)
            .cost(1)
            .event()
            .mutation(ResourceMutation(Heat, -5))
            .mutation(ResourceMutation(Plant, 4))
            .build()),
        (191, CardBuilder::new()
            .id(1)
            .cost(8)
            .event()
            .requirement(Requirement::MinTemperature(-8))
            .mutation(TileQueuingMutation(Ocean))
            .build()),
        (193, CardBuilder::new()
            .id(3)
            .cost(15)
            .tags(vec![Tag::Plant])
            .requirement(Requirement::Tag(Science, 2))
            .mutation(TileQueuingMutation(Greenery))
            .build()),
        (203, CardBuilder::new()
            .id(3)
            .cost(35)
            .tags(vec![Space])
            .mutation(ProductionMutation(Heat, 7))
            .build()),
        (205, CardBuilder::new()
            .id(5)
            .cost(8)
            .tags(vec![Builder])
            .mutation(ProductionMutation(Energy, -1))
            .mutation(TrMutation(2))
            .build()),
    ])
}

fn space_event() -> CardBuilder {
    CardBuilder::new()
        .tags(vec![Space])
        .event()
}

fn martian_city() -> CardBuilder {
    CardBuilder::new()
        .tags(vec![City, Builder])
        .mutation(ResourceMutation(Energy, -1))
        .mutation(TileQueuingMutation(Tile::City))
}